### ISSUE TITLE
Not showing the big play button on hover

### ISSUE THREAD

**Issue by thema-d** [google/shaka-player#2319]
Hey great folks,
Can someone please give me a hint about how to hide the big play button on hover and instead make it look like youtube one, it appears when clicked and fades away after a while?
Thanks

**Comment by thema-d** [comment]
@joeyparrish help me :)

**Comment by joeyparrish** [comment]
You can do a lot with a small amount of JS & CSS.  You don't have to change anything in Shaka Player itself to get the effect you described.

What I observed on YouTube was that the button shows up only when you click, then fades away quickly after.  It also shows the icon of what action you're doing, not what the button will do the next time you click it.  (This is the opposite of Shaka.)

First off, you can change the styles of that UI element by styling the class `.shaka-play-button`.  You can discover this by using the DOM inspector in your browser's dev tools.

For example:

```css
.shaka-play-button {
    opacity: 0;
}
.shaka-play-button.show-me {
    opacity: 1;
}
```

Add that CSS to your app after ours.  Now the button is hidden unless you attach the `show-me` class to it.  It still takes up space and responds to clicks, though.  And because we're using opacity, you can add a transition to the hiding of it:

```css
/* Only affects the button when we hide it.  This means no transition when we show it.
 * Pops in instantly, fades out over 500ms. */
.shaka-play-button:not(.show-me) {
  transition: opacity 0.5s;
}
```

Now you can use the video element & JS to activate those CSS changes.  I would suggest you listen to the `pause` and `play` events on the video to modify the classes of the giant play button.

For example:

```js
let timerId = null;
function onStateChange() {
  clearTimeout(timerId);

  // Show the button, then quickly hide it again.  The transition will animate hiding it.
  const button = document.querySelector('.shaka-play-button');
  button.classList.add('show-me');
  timerId = setTimeout(() => button.classList.remove('show-me'), 100);
}

// Do this on both pause and play.
video.addEventListener('pause', onStateChange);
video.addEventListener('play', onStateChange);
```

Finally, you want to change the icon that is shown, since YouTube's icons are the reverse of what we show.  You can do this in CSS also.  If you inspect our styles in the browser's dev tools, you'll see:

```css
.shaka-play-button[icon="play"] {
  background-image: url('https://shaka-player-demo.appspot.com/ui/images/play_arrow.svg');
}

.shaka-play-button[icon="pause"] {
  background-image: url('https://shaka-player-demo.appspot.com/ui/images/pause.svg');
}
```

To completely match YouTube's style, you'd want to reverse this, so that the icon shows the action you're taking, not what the button will do next time you click it.  So just add these styles to your app:

```css
.shaka-play-button[icon="pause"] {
  background-image: url('https://shaka-player-demo.appspot.com/ui/images/play_arrow.svg');
}

.shaka-play-button[icon="play"] {
  background-image: url('https://shaka-player-demo.appspot.com/ui/images/pause.svg');
}
```

I tested all of this in the Shaka Player demo, and it seems to match YouTube's style fairly closely.

The only thing that's missing is the permanent play/pause button, which you can add by configuring the UI to add "play_pause" to the controls.  See the ["Customizing the UI"](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui-customization.html) tutorial for details.

Overall, there are lots of possibilities to re-style things with CSS.  We tried to give everything a simple class name, and you can discover them in dev tools or by [reading the source of our CSS/LESS files](https://github.com/google/shaka-player/tree/master/ui/less).  And MDN has [a great reference for HTML5 media events](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement#Events) you can use to trigger things.

Does this help?
