### ISSUE TITLE
Styling subtitles

### ISSUE THREAD

**Issue by Kotekczu** [google/shaka-player#3174]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?**
Yes.

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes.

**What version of Shaka Player are you using?**
3.0.8.

**Please ask your question**
What's the appropiate way to set the style for subtitles, such as font and size? I've also noticed subtitles size isn't responsive when switching between full screen mode and window mode once they show up.

**Comment by TheModMaker** [comment]
That depends on a few things.  You can style the subtitles in the files themselves.  We already support styling in TTML and with #3071 we'll support global styling in WebVTT (i.e. not per-cue styling).  However, if not using our UI, styling in the files may not be supported.

If you want to style them outside the subtitle files, you can use CSS.  If you're not using our UI, you can style them with the `::cue` selector.  If you're using our UI, you can style them with `.shaka-text-container`.  For example:

```css
/* Styling with no UI. */
video::cue {
  font-size: 12pt;
}

/* Styling with UI. */
.shaka-text-container {
  color: red;
}

/* Styling with UI, only when fullscreen (may not be supported in some browsers). */
.shaka-text-container:fullscreen {
  font-size: 18pt;
}
```

You may need to use `!important` to make these override the styles specified in the subtitle files.
