### ISSUE TITLE
Need help generating a DASH compatible webm file.

### ISSUE THREAD

**Issue by upanitag** [google/shaka-player#3661]
Hi, 
I have followed the steps described here : http://wiki.webmproject.org/adaptive-streaming/instructions-to-playback-adaptive-webm-using-dash. During playback, I get an error. I am using Shaka Player.

Output from browser console.
The video has now been loaded!
myplayer.html:57 Error code 3007 object OÂ {severity: 2, category: 3, code: 3007, data: Array(0), handled: false} 

According to Shaka player error code, 3007 means : WEBM_CUES_ELEMENT_MISSING	3007	number 	The WebM Cues parser was unable to locate the Cues element. The segment index data may be corrupt.

How do I fix this error?

My steps
1.	ffmpeg -i  blue_sky_1080p25.y4m -c:v libvpx-vp9 -s 160x90 -b:v 250k -keyint_min 150 -g 150  -tile-columns 4 -frame-parallel 1  -an -f webm -dash 1  sky_160x90_250k.webm
2.	ffmpeg -f webm_dash_manifest -i  sky_160x90_250k.webm -c copy -map 0 -f webm_dash_manifest -adaptation_sets "id=0,streams=video" manifest.mpd

I provide this manifest file to the shaka player

Thanks,
Upanita

**Comment by joeyparrish** [comment]
I don't know that FFmpeg's direct DASH output is correct.  I would suggest you try something like [Shaka Streamer](https://github.com/google/shaka-streamer/) for content preparation instead.  It uses FFmpeg internally for transcoding, but [Shaka Packager](https://github.com/google/shaka-packager/) for fragmenting and packaging in DASH.  For example, this may work for your y4m input file:

```yaml
# input.yaml

inputs:
  - name: blue_sky_1080p25.y4m
    extra_input_args: -s 160x90
    width: 160
    height: 90
    media_type: video
```

```yaml
# pipeline.yaml

video_codecs:
  - vp9

manifest_format:
  - dash

segment_size: 4
segment_per_file: True
```

```sh
pip3 install --upgrade shaka-streamer shaka-streamer-binaries
shaka-streamer -i input.yaml -p pipeline.yaml -o output/
```

All output will be written to the `output/` folder in this example, and the manifest will be `output/dash.mpd`.

See also the [full Shaka Streamer docs](https://google.github.io/shaka-streamer/index.html) for more info.

Does this help?
